# Generated by Django 5.2.5 on 2025-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
